# Generated by Django 5.2 on 2025-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_mobile',
            field=models.CharField(max_length=11),
        ),
    ]
